// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikey.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (merchant_id, name, key_hash, key_prefix, type, mode, scope, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, merchant_id, name, key_hash, key_prefix, type, mode, scope, last_used_at, expires_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	MerchantID pgtype.UUID        `json:"merchant_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Type       string             `json:"type"`
	Mode       string             `json:"mode"`
	Scope      []string           `json:"scope"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.MerchantID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Type,
		arg.Mode,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Type,
		&i.Mode,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, merchant_id, name, key_hash, key_prefix, type, mode, scope, last_used_at, expires_at, created_at, revoked_at FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Type,
		&i.Mode,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, merchant_id, name, key_hash, key_prefix, type, mode, scope, last_used_at, expires_at, created_at, revoked_at FROM api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Type,
		&i.Mode,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysByMerchant = `-- name: ListAPIKeysByMerchant :many
SELECT id, merchant_id, name, key_hash, key_prefix, type, mode, scope, last_used_at, expires_at, created_at, revoked_at FROM api_keys
WHERE merchant_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Type,
			&i.Mode,
			&i.Scope,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND revoked_at IS NULL
RETURNING id, merchant_id, name, key_hash, key_prefix, type, mode, scope, last_used_at, expires_at, created_at, revoked_at
`

type RevokeAPIKeyParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.MerchantID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Type,
		&i.Mode,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
