// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (merchant_id, actor_type, actor_id, action, resource, resource_id, diff, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateAuditLogParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	ActorType  string      `json:"actor_type"`
	ActorID    string      `json:"actor_id"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Diff       []byte      `json:"diff"`
	IpAddress  *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.MerchantID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Diff,
		arg.IpAddress,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
