// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharge = `-- name: CreateCharge :one
INSERT INTO charges (
  merchant_id, customer_id, payment_method_id, amount, currency, status,
  processor, processor_charge_id, idempotency_key, mode, failure_code,
  failure_message, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, merchant_id, customer_id, payment_method_id, amount, currency, status, processor, processor_charge_id, idempotency_key, mode, failure_code, failure_message, refunded_amount, metadata, created_at, updated_at, deleted_at
`

type CreateChargeParams struct {
	MerchantID        pgtype.UUID `json:"merchant_id"`
	CustomerID        pgtype.UUID `json:"customer_id"`
	PaymentMethodID   pgtype.UUID `json:"payment_method_id"`
	Amount            int64       `json:"amount"`
	Currency          string      `json:"currency"`
	Status            string      `json:"status"`
	Processor         string      `json:"processor"`
	ProcessorChargeID *string     `json:"processor_charge_id"`
	IdempotencyKey    *string     `json:"idempotency_key"`
	Mode              string      `json:"mode"`
	FailureCode       *string     `json:"failure_code"`
	FailureMessage    *string     `json:"failure_message"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) (Charge, error) {
	row := q.db.QueryRow(ctx, createCharge,
		arg.MerchantID,
		arg.CustomerID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.Processor,
		arg.ProcessorChargeID,
		arg.IdempotencyKey,
		arg.Mode,
		arg.FailureCode,
		arg.FailureMessage,
		arg.Metadata,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorChargeID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureCode,
		&i.FailureMessage,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCharge = `-- name: GetCharge :one
SELECT id, merchant_id, customer_id, payment_method_id, amount, currency, status, processor, processor_charge_id, idempotency_key, mode, failure_code, failure_message, refunded_amount, metadata, created_at, updated_at, deleted_at FROM charges
WHERE id = $1 AND merchant_id = $2 AND mode = $3 AND deleted_at IS NULL
`

type GetChargeParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

func (q *Queries) GetCharge(ctx context.Context, arg GetChargeParams) (Charge, error) {
	row := q.db.QueryRow(ctx, getCharge, arg.ID, arg.MerchantID, arg.Mode)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorChargeID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureCode,
		&i.FailureMessage,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChargeByProcessorID = `-- name: GetChargeByProcessorID :one
SELECT id, merchant_id, customer_id, payment_method_id, amount, currency, status, processor, processor_charge_id, idempotency_key, mode, failure_code, failure_message, refunded_amount, metadata, created_at, updated_at, deleted_at FROM charges
WHERE processor_charge_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetChargeByProcessorID(ctx context.Context, processorChargeID *string) (Charge, error) {
	row := q.db.QueryRow(ctx, getChargeByProcessorID, processorChargeID)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorChargeID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureCode,
		&i.FailureMessage,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCharges = `-- name: ListCharges :many
SELECT id, merchant_id, customer_id, payment_method_id, amount, currency, status, processor, processor_charge_id, idempotency_key, mode, failure_code, failure_message, refunded_amount, metadata, created_at, updated_at, deleted_at FROM charges
WHERE merchant_id = $1
  AND mode = $2
  AND deleted_at IS NULL
  AND ($4::text IS NULL OR status = $4)
  AND (
    $5::timestamptz IS NULL
    OR created_at < $5
    OR (created_at = $5 AND id < $6)
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListChargesParams struct {
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Mode          string             `json:"mode"`
	Limit         int32              `json:"limit"`
	Status        *string            `json:"status"`
	CursorCreated pgtype.Timestamptz `json:"cursor_created"`
	CursorID      pgtype.UUID        `json:"cursor_id"`
}

// Mode-isolated, merchant-scoped, newest first. Optional status filter and
// keyset cursor are passed as nullable args (sqlc.narg); when NULL they are
// no-ops. Keyset written as explicit booleans so sqlc types the params.
func (q *Queries) ListCharges(ctx context.Context, arg ListChargesParams) ([]Charge, error) {
	rows, err := q.db.Query(ctx, listCharges,
		arg.MerchantID,
		arg.Mode,
		arg.Limit,
		arg.Status,
		arg.CursorCreated,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Charge
	for rows.Next() {
		var i Charge
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Processor,
			&i.ProcessorChargeID,
			&i.IdempotencyKey,
			&i.Mode,
			&i.FailureCode,
			&i.FailureMessage,
			&i.RefundedAmount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChargeRefund = `-- name: UpdateChargeRefund :one
UPDATE charges
SET refunded_amount = $3, status = $4, updated_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
RETURNING id, merchant_id, customer_id, payment_method_id, amount, currency, status, processor, processor_charge_id, idempotency_key, mode, failure_code, failure_message, refunded_amount, metadata, created_at, updated_at, deleted_at
`

type UpdateChargeRefundParams struct {
	ID             pgtype.UUID `json:"id"`
	MerchantID     pgtype.UUID `json:"merchant_id"`
	RefundedAmount int64       `json:"refunded_amount"`
	Status         string      `json:"status"`
}

func (q *Queries) UpdateChargeRefund(ctx context.Context, arg UpdateChargeRefundParams) (Charge, error) {
	row := q.db.QueryRow(ctx, updateChargeRefund,
		arg.ID,
		arg.MerchantID,
		arg.RefundedAmount,
		arg.Status,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorChargeID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureCode,
		&i.FailureMessage,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateChargeStatusByProcessorID = `-- name: UpdateChargeStatusByProcessorID :one
UPDATE charges
SET status = $2, failure_code = $3, failure_message = $4, updated_at = NOW()
WHERE processor_charge_id = $1 AND deleted_at IS NULL
RETURNING id, merchant_id, customer_id, payment_method_id, amount, currency, status, processor, processor_charge_id, idempotency_key, mode, failure_code, failure_message, refunded_amount, metadata, created_at, updated_at, deleted_at
`

type UpdateChargeStatusByProcessorIDParams struct {
	ProcessorChargeID *string `json:"processor_charge_id"`
	Status            string  `json:"status"`
	FailureCode       *string `json:"failure_code"`
	FailureMessage    *string `json:"failure_message"`
}

func (q *Queries) UpdateChargeStatusByProcessorID(ctx context.Context, arg UpdateChargeStatusByProcessorIDParams) (Charge, error) {
	row := q.db.QueryRow(ctx, updateChargeStatusByProcessorID,
		arg.ProcessorChargeID,
		arg.Status,
		arg.FailureCode,
		arg.FailureMessage,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorChargeID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureCode,
		&i.FailureMessage,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
