// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (merchant_id, email, name, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, email, name, metadata, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Email      *string     `json:"email"`
	Name       *string     `json:"name"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.MerchantID,
		arg.Email,
		arg.Name,
		arg.Metadata,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, merchant_id, email, name, metadata, created_at, updated_at, deleted_at FROM customers
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
`

type GetCustomerParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.ID, arg.MerchantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomersAfter = `-- name: ListCustomersAfter :many
SELECT id, merchant_id, email, name, metadata, created_at, updated_at, deleted_at FROM customers
WHERE merchant_id = $1 AND deleted_at IS NULL
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListCustomersAfterParams struct {
	MerchantID pgtype.UUID        `json:"merchant_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ID         pgtype.UUID        `json:"id"`
	Limit      int32              `json:"limit"`
}

// Keyset pagination: rows strictly "after" the (created_at, id) cursor under the
// DESC ordering. Written as explicit boolean logic (rather than a row-value
// comparison) so sqlc infers $2 as timestamptz and $3 as uuid.
func (q *Queries) ListCustomersAfter(ctx context.Context, arg ListCustomersAfterParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersAfter,
		arg.MerchantID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Email,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersFirst = `-- name: ListCustomersFirst :many
SELECT id, merchant_id, email, name, metadata, created_at, updated_at, deleted_at FROM customers
WHERE merchant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListCustomersFirstParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListCustomersFirst(ctx context.Context, arg ListCustomersFirstParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersFirst, arg.MerchantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Email,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :one
UPDATE customers
SET deleted_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteCustomerParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteCustomer, arg.ID, arg.MerchantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET email = $3, name = $4, metadata = $5, updated_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
RETURNING id, merchant_id, email, name, metadata, created_at, updated_at, deleted_at
`

type UpdateCustomerParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	Email      *string     `json:"email"`
	Name       *string     `json:"name"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.MerchantID,
		arg.Email,
		arg.Name,
		arg.Metadata,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
