// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chargeStatsByMode = `-- name: ChargeStatsByMode :one
SELECT
  COUNT(*)                                                        AS total_count,
  COUNT(*) FILTER (WHERE status = 'succeeded')                    AS succeeded_count,
  COALESCE(SUM(amount) FILTER (WHERE status = 'succeeded'), 0)::bigint AS succeeded_volume,
  COUNT(*) FILTER (WHERE status = 'failed')                       AS failed_count
FROM charges
WHERE merchant_id = $1 AND mode = $2 AND deleted_at IS NULL
`

type ChargeStatsByModeParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

type ChargeStatsByModeRow struct {
	TotalCount      int64 `json:"total_count"`
	SucceededCount  int64 `json:"succeeded_count"`
	SucceededVolume int64 `json:"succeeded_volume"`
	FailedCount     int64 `json:"failed_count"`
}

// Aggregate charge volume for a merchant+mode: total count, succeeded count,
// and gross succeeded volume (minor units).
func (q *Queries) ChargeStatsByMode(ctx context.Context, arg ChargeStatsByModeParams) (ChargeStatsByModeRow, error) {
	row := q.db.QueryRow(ctx, chargeStatsByMode, arg.MerchantID, arg.Mode)
	var i ChargeStatsByModeRow
	err := row.Scan(
		&i.TotalCount,
		&i.SucceededCount,
		&i.SucceededVolume,
		&i.FailedCount,
	)
	return i, err
}

const recentFailedCharges = `-- name: RecentFailedCharges :many
SELECT id, merchant_id, customer_id, payment_method_id, amount, currency, status, processor, processor_charge_id, idempotency_key, mode, failure_code, failure_message, refunded_amount, metadata, created_at, updated_at, deleted_at FROM charges
WHERE merchant_id = $1 AND mode = $2 AND status = 'failed' AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3
`

type RecentFailedChargesParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) RecentFailedCharges(ctx context.Context, arg RecentFailedChargesParams) ([]Charge, error) {
	rows, err := q.db.Query(ctx, recentFailedCharges, arg.MerchantID, arg.Mode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Charge
	for rows.Next() {
		var i Charge
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Processor,
			&i.ProcessorChargeID,
			&i.IdempotencyKey,
			&i.Mode,
			&i.FailureCode,
			&i.FailureMessage,
			&i.RefundedAmount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
