// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, name, currency, type, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, name, currency, type, created_at
`

type CreateAccountParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
	Type     string `json:"type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.Type,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, account_id, amount, direction, currency, memo, transaction_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, account_id, amount, direction, currency, memo, transaction_id, created_at
`

type CreateEntryParams struct {
	ID            string `json:"id"`
	AccountID     string `json:"account_id"`
	Amount        int64  `json:"amount"`
	Direction     int16  `json:"direction"`
	Currency      string `json:"currency"`
	Memo          string `json:"memo"`
	TransactionID string `json:"transaction_id"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Direction,
		arg.Currency,
		arg.Memo,
		arg.TransactionID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Direction,
		&i.Currency,
		&i.Memo,
		&i.TransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, currency, type, created_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getEntriesByAccount = `-- name: GetEntriesByAccount :many
SELECT id, account_id, amount, direction, currency, memo, transaction_id, created_at FROM entries
WHERE account_id = $1
ORDER BY created_at
`

func (q *Queries) GetEntriesByAccount(ctx context.Context, accountID string) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.Currency,
			&i.Memo,
			&i.TransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByTransaction = `-- name: GetEntriesByTransaction :many
SELECT id, account_id, amount, direction, currency, memo, transaction_id, created_at FROM entries
WHERE transaction_id = $1
ORDER BY created_at
`

func (q *Queries) GetEntriesByTransaction(ctx context.Context, transactionID string) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.Currency,
			&i.Memo,
			&i.TransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, currency, type, created_at FROM accounts
ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
