// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (email, password_hash, business_name, mode)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, business_name, mode, created_at, updated_at, deleted_at
`

type CreateMerchantParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	BusinessName string `json:"business_name"`
	Mode         string `json:"mode"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.Email,
		arg.PasswordHash,
		arg.BusinessName,
		arg.Mode,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.BusinessName,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT id, email, password_hash, business_name, mode, created_at, updated_at, deleted_at FROM merchants
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, email string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByEmail, email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.BusinessName,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, email, password_hash, business_name, mode, created_at, updated_at, deleted_at FROM merchants
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMerchantByID(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.BusinessName,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
