// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Currency  string             `json:"currency"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID            string             `json:"id"`
	AccountID     string             `json:"account_id"`
	Amount        int64              `json:"amount"`
	Direction     int16              `json:"direction"`
	Currency      string             `json:"currency"`
	Memo          string             `json:"memo"`
	TransactionID string             `json:"transaction_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID             string             `json:"id"`
	Amount         int64              `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	ProviderRef    string             `json:"provider_ref"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
