// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payout.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingPayouts = `-- name: CountPendingPayouts :one
SELECT COUNT(*) FROM payouts
WHERE merchant_id = $1 AND mode = $2 AND status IN ('pending','in_transit') AND deleted_at IS NULL
`

type CountPendingPayoutsParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

func (q *Queries) CountPendingPayouts(ctx context.Context, arg CountPendingPayoutsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingPayouts, arg.MerchantID, arg.Mode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO bank_accounts (merchant_id, processor, processor_acct_id, last4, bank_name, currency, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, processor, processor_acct_id, last4, bank_name, currency, is_default, created_at, deleted_at
`

type CreateBankAccountParams struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	Processor       string      `json:"processor"`
	ProcessorAcctID string      `json:"processor_acct_id"`
	Last4           *string     `json:"last4"`
	BankName        *string     `json:"bank_name"`
	Currency        *string     `json:"currency"`
	IsDefault       bool        `json:"is_default"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.MerchantID,
		arg.Processor,
		arg.ProcessorAcctID,
		arg.Last4,
		arg.BankName,
		arg.Currency,
		arg.IsDefault,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Processor,
		&i.ProcessorAcctID,
		&i.Last4,
		&i.BankName,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (
  merchant_id, bank_account_id, amount, currency, status, processor,
  processor_payout_id, idempotency_key, mode, arrival_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, merchant_id, bank_account_id, amount, currency, status, processor, processor_payout_id, idempotency_key, mode, failure_message, arrival_date, created_at, updated_at, deleted_at
`

type CreatePayoutParams struct {
	MerchantID        pgtype.UUID `json:"merchant_id"`
	BankAccountID     pgtype.UUID `json:"bank_account_id"`
	Amount            int64       `json:"amount"`
	Currency          string      `json:"currency"`
	Status            string      `json:"status"`
	Processor         string      `json:"processor"`
	ProcessorPayoutID *string     `json:"processor_payout_id"`
	IdempotencyKey    *string     `json:"idempotency_key"`
	Mode              string      `json:"mode"`
	ArrivalDate       pgtype.Date `json:"arrival_date"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.MerchantID,
		arg.BankAccountID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.Processor,
		arg.ProcessorPayoutID,
		arg.IdempotencyKey,
		arg.Mode,
		arg.ArrivalDate,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BankAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorPayoutID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureMessage,
		&i.ArrivalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT id, merchant_id, processor, processor_acct_id, last4, bank_name, currency, is_default, created_at, deleted_at FROM bank_accounts
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
`

type GetBankAccountParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) GetBankAccount(ctx context.Context, arg GetBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccount, arg.ID, arg.MerchantID)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Processor,
		&i.ProcessorAcctID,
		&i.Last4,
		&i.BankName,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPayout = `-- name: GetPayout :one
SELECT id, merchant_id, bank_account_id, amount, currency, status, processor, processor_payout_id, idempotency_key, mode, failure_message, arrival_date, created_at, updated_at, deleted_at FROM payouts
WHERE id = $1 AND merchant_id = $2 AND mode = $3 AND deleted_at IS NULL
`

type GetPayoutParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

func (q *Queries) GetPayout(ctx context.Context, arg GetPayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayout, arg.ID, arg.MerchantID, arg.Mode)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BankAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorPayoutID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureMessage,
		&i.ArrivalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, merchant_id, processor, processor_acct_id, last4, bank_name, currency, is_default, created_at, deleted_at FROM bank_accounts
WHERE merchant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListBankAccounts(ctx context.Context, merchantID pgtype.UUID) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, listBankAccounts, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Processor,
			&i.ProcessorAcctID,
			&i.Last4,
			&i.BankName,
			&i.Currency,
			&i.IsDefault,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayouts = `-- name: ListPayouts :many
SELECT id, merchant_id, bank_account_id, amount, currency, status, processor, processor_payout_id, idempotency_key, mode, failure_message, arrival_date, created_at, updated_at, deleted_at FROM payouts
WHERE merchant_id = $1
  AND mode = $2
  AND deleted_at IS NULL
  AND (
    $4::timestamptz IS NULL
    OR created_at < $4
    OR (created_at = $4 AND id < $5)
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListPayoutsParams struct {
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Mode          string             `json:"mode"`
	Limit         int32              `json:"limit"`
	CursorCreated pgtype.Timestamptz `json:"cursor_created"`
	CursorID      pgtype.UUID        `json:"cursor_id"`
}

func (q *Queries) ListPayouts(ctx context.Context, arg ListPayoutsParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayouts,
		arg.MerchantID,
		arg.Mode,
		arg.Limit,
		arg.CursorCreated,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.BankAccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Processor,
			&i.ProcessorPayoutID,
			&i.IdempotencyKey,
			&i.Mode,
			&i.FailureMessage,
			&i.ArrivalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBankAccount = `-- name: SoftDeleteBankAccount :one
UPDATE bank_accounts
SET deleted_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteBankAccountParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) SoftDeleteBankAccount(ctx context.Context, arg SoftDeleteBankAccountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteBankAccount, arg.ID, arg.MerchantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updatePayoutStatusByProcessorID = `-- name: UpdatePayoutStatusByProcessorID :one
UPDATE payouts
SET status = $2, failure_message = $3, updated_at = NOW()
WHERE processor_payout_id = $1 AND deleted_at IS NULL
RETURNING id, merchant_id, bank_account_id, amount, currency, status, processor, processor_payout_id, idempotency_key, mode, failure_message, arrival_date, created_at, updated_at, deleted_at
`

type UpdatePayoutStatusByProcessorIDParams struct {
	ProcessorPayoutID *string `json:"processor_payout_id"`
	Status            string  `json:"status"`
	FailureMessage    *string `json:"failure_message"`
}

func (q *Queries) UpdatePayoutStatusByProcessorID(ctx context.Context, arg UpdatePayoutStatusByProcessorIDParams) (Payout, error) {
	row := q.db.QueryRow(ctx, updatePayoutStatusByProcessorID, arg.ProcessorPayoutID, arg.Status, arg.FailureMessage)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BankAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Processor,
		&i.ProcessorPayoutID,
		&i.IdempotencyKey,
		&i.Mode,
		&i.FailureMessage,
		&i.ArrivalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
