// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (merchant_id, token_hash, jti, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, token_hash, jti, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	MerchantID pgtype.UUID        `json:"merchant_id"`
	TokenHash  string             `json:"token_hash"`
	Jti        string             `json:"jti"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.MerchantID,
		arg.TokenHash,
		arg.Jti,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TokenHash,
		&i.Jti,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, merchant_id, token_hash, jti, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TokenHash,
		&i.Jti,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :one
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
RETURNING id, merchant_id, token_hash, jti, expires_at, revoked_at, created_at
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, revokeRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TokenHash,
		&i.Jti,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshTokenByJTI = `-- name: RevokeRefreshTokenByJTI :one
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE jti = $1 AND revoked_at IS NULL
RETURNING id, merchant_id, token_hash, jti, expires_at, revoked_at, created_at
`

func (q *Queries) RevokeRefreshTokenByJTI(ctx context.Context, jti string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, revokeRefreshTokenByJTI, jti)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TokenHash,
		&i.Jti,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
