// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one
SELECT COUNT(*) FROM subscriptions
WHERE merchant_id = $1 AND mode = $2 AND status = 'active' AND deleted_at IS NULL
`

type CountActiveSubscriptionsParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

func (q *Queries) CountActiveSubscriptions(ctx context.Context, arg CountActiveSubscriptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptions, arg.MerchantID, arg.Mode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (merchant_id, name, amount, currency, interval, interval_count, processor_plan_id, mode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, merchant_id, name, amount, currency, interval, interval_count, processor_plan_id, mode, created_at, deleted_at
`

type CreatePlanParams struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	Name            string      `json:"name"`
	Amount          int64       `json:"amount"`
	Currency        string      `json:"currency"`
	Interval        string      `json:"interval"`
	IntervalCount   int16       `json:"interval_count"`
	ProcessorPlanID *string     `json:"processor_plan_id"`
	Mode            string      `json:"mode"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.MerchantID,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.Interval,
		arg.IntervalCount,
		arg.ProcessorPlanID,
		arg.Mode,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.IntervalCount,
		&i.ProcessorPlanID,
		&i.Mode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  merchant_id, customer_id, plan_id, payment_method_id, status, processor_sub_id,
  current_period_start, current_period_end, trial_end, mode, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, merchant_id, customer_id, plan_id, payment_method_id, status, processor_sub_id, current_period_start, current_period_end, trial_end, canceled_at, mode, metadata, created_at, updated_at, deleted_at
`

type CreateSubscriptionParams struct {
	MerchantID         pgtype.UUID        `json:"merchant_id"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	PlanID             pgtype.UUID        `json:"plan_id"`
	PaymentMethodID    pgtype.UUID        `json:"payment_method_id"`
	Status             string             `json:"status"`
	ProcessorSubID     *string            `json:"processor_sub_id"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	TrialEnd           pgtype.Timestamptz `json:"trial_end"`
	Mode               string             `json:"mode"`
	Metadata           []byte             `json:"metadata"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.MerchantID,
		arg.CustomerID,
		arg.PlanID,
		arg.PaymentMethodID,
		arg.Status,
		arg.ProcessorSubID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialEnd,
		arg.Mode,
		arg.Metadata,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PlanID,
		&i.PaymentMethodID,
		&i.Status,
		&i.ProcessorSubID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CanceledAt,
		&i.Mode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, merchant_id, name, amount, currency, interval, interval_count, processor_plan_id, mode, created_at, deleted_at FROM plans
WHERE id = $1 AND merchant_id = $2 AND mode = $3 AND deleted_at IS NULL
`

type GetPlanParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, arg.ID, arg.MerchantID, arg.Mode)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.IntervalCount,
		&i.ProcessorPlanID,
		&i.Mode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, merchant_id, customer_id, plan_id, payment_method_id, status, processor_sub_id, current_period_start, current_period_end, trial_end, canceled_at, mode, metadata, created_at, updated_at, deleted_at FROM subscriptions
WHERE id = $1 AND merchant_id = $2 AND mode = $3 AND deleted_at IS NULL
`

type GetSubscriptionParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.ID, arg.MerchantID, arg.Mode)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PlanID,
		&i.PaymentMethodID,
		&i.Status,
		&i.ProcessorSubID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CanceledAt,
		&i.Mode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, merchant_id, name, amount, currency, interval, interval_count, processor_plan_id, mode, created_at, deleted_at FROM plans
WHERE merchant_id = $1 AND mode = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListPlansParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.Interval,
			&i.IntervalCount,
			&i.ProcessorPlanID,
			&i.Mode,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, merchant_id, customer_id, plan_id, payment_method_id, status, processor_sub_id, current_period_start, current_period_end, trial_end, canceled_at, mode, metadata, created_at, updated_at, deleted_at FROM subscriptions
WHERE merchant_id = $1
  AND mode = $2
  AND deleted_at IS NULL
  AND ($4::text IS NULL OR status = $4)
  AND (
    $5::timestamptz IS NULL
    OR created_at < $5
    OR (created_at = $5 AND id < $6)
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListSubscriptionsParams struct {
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Mode          string             `json:"mode"`
	Limit         int32              `json:"limit"`
	Status        *string            `json:"status"`
	CursorCreated pgtype.Timestamptz `json:"cursor_created"`
	CursorID      pgtype.UUID        `json:"cursor_id"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.MerchantID,
		arg.Mode,
		arg.Limit,
		arg.Status,
		arg.CursorCreated,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.PlanID,
			&i.PaymentMethodID,
			&i.Status,
			&i.ProcessorSubID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.TrialEnd,
			&i.CanceledAt,
			&i.Mode,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubscriptionStatus = `-- name: SetSubscriptionStatus :one
UPDATE subscriptions
SET status = $3,
    canceled_at = CASE WHEN $4::bool THEN NOW() ELSE canceled_at END,
    updated_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
RETURNING id, merchant_id, customer_id, plan_id, payment_method_id, status, processor_sub_id, current_period_start, current_period_end, trial_end, canceled_at, mode, metadata, created_at, updated_at, deleted_at
`

type SetSubscriptionStatusParams struct {
	ID          pgtype.UUID `json:"id"`
	MerchantID  pgtype.UUID `json:"merchant_id"`
	Status      string      `json:"status"`
	SetCanceled bool        `json:"set_canceled"`
}

func (q *Queries) SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, setSubscriptionStatus,
		arg.ID,
		arg.MerchantID,
		arg.Status,
		arg.SetCanceled,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PlanID,
		&i.PaymentMethodID,
		&i.Status,
		&i.ProcessorSubID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CanceledAt,
		&i.Mode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeletePlan = `-- name: SoftDeletePlan :one
UPDATE plans
SET deleted_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeletePlanParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeletePlan, arg.ID, arg.MerchantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateSubscriptionStatusByProcessorID = `-- name: UpdateSubscriptionStatusByProcessorID :one
UPDATE subscriptions
SET status = $2,
    canceled_at = CASE WHEN $2 = 'canceled' THEN NOW() ELSE canceled_at END,
    updated_at = NOW()
WHERE processor_sub_id = $1 AND deleted_at IS NULL
RETURNING id, merchant_id, customer_id, plan_id, payment_method_id, status, processor_sub_id, current_period_start, current_period_end, trial_end, canceled_at, mode, metadata, created_at, updated_at, deleted_at
`

type UpdateSubscriptionStatusByProcessorIDParams struct {
	ProcessorSubID *string `json:"processor_sub_id"`
	Status         string  `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatusByProcessorID(ctx context.Context, arg UpdateSubscriptionStatusByProcessorIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatusByProcessorID, arg.ProcessorSubID, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PlanID,
		&i.PaymentMethodID,
		&i.Status,
		&i.ProcessorSubID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CanceledAt,
		&i.Mode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
