// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (endpoint_id, event_type, payload, status, next_retry_at)
VALUES ($1, $2, $3, 'pending', NOW())
RETURNING id
`

type CreateWebhookDeliveryParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	EventType  string      `json:"event_type"`
	Payload    []byte      `json:"payload"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.EndpointID, arg.EventType, arg.Payload)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const dueWebhookDeliveries = `-- name: DueWebhookDeliveries :many
SELECT d.id, d.endpoint_id, d.event_type, d.payload, d.attempt_count, e.url
FROM webhook_deliveries d
JOIN webhook_endpoints e ON e.id = d.endpoint_id
WHERE d.status = 'pending'
  AND d.next_retry_at <= NOW()
ORDER BY d.next_retry_at
LIMIT $1
`

type DueWebhookDeliveriesRow struct {
	ID           pgtype.UUID `json:"id"`
	EndpointID   pgtype.UUID `json:"endpoint_id"`
	EventType    string      `json:"event_type"`
	Payload      []byte      `json:"payload"`
	AttemptCount int16       `json:"attempt_count"`
	Url          string      `json:"url"`
}

func (q *Queries) DueWebhookDeliveries(ctx context.Context, limit int32) ([]DueWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, dueWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueWebhookDeliveriesRow
	for rows.Next() {
		var i DueWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventType,
			&i.Payload,
			&i.AttemptCount,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishWebhookDeliveryAttempt = `-- name: FinishWebhookDeliveryAttempt :exec
UPDATE webhook_deliveries
SET status               = $2,
    attempt_count        = attempt_count + 1,
    next_retry_at        = $3,
    last_response_status = $4,
    last_response_body   = $5,
    updated_at           = NOW()
WHERE id = $1
`

type FinishWebhookDeliveryAttemptParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Status             string             `json:"status"`
	NextRetryAt        pgtype.Timestamptz `json:"next_retry_at"`
	LastResponseStatus *int32             `json:"last_response_status"`
	LastResponseBody   *string            `json:"last_response_body"`
}

func (q *Queries) FinishWebhookDeliveryAttempt(ctx context.Context, arg FinishWebhookDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, finishWebhookDeliveryAttempt,
		arg.ID,
		arg.Status,
		arg.NextRetryAt,
		arg.LastResponseStatus,
		arg.LastResponseBody,
	)
	return err
}

const listActiveWebhookEndpoints = `-- name: ListActiveWebhookEndpoints :many

SELECT id, url
FROM webhook_endpoints
WHERE merchant_id = $1
  AND mode = $2
  AND is_active
  AND deleted_at IS NULL
  AND $3::text = ANY(events)
`

type ListActiveWebhookEndpointsParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Mode       string      `json:"mode"`
	EventType  string      `json:"event_type"`
}

type ListActiveWebhookEndpointsRow struct {
	ID  pgtype.UUID `json:"id"`
	Url string      `json:"url"`
}

// Outbound webhook endpoints + delivery log (build.md Phase 7).
// All queries are parameterized; the delivery loop is driven by status +
// next_retry_at, so a single UPDATE shape records every attempt outcome.
func (q *Queries) ListActiveWebhookEndpoints(ctx context.Context, arg ListActiveWebhookEndpointsParams) ([]ListActiveWebhookEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookEndpoints, arg.MerchantID, arg.Mode, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveWebhookEndpointsRow
	for rows.Next() {
		var i ListActiveWebhookEndpointsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
